apiVersion: apps/v1
kind: Deployment
metadata:
  name: plant-pathology-app-deployment
  labels:
    app: plant-pathology-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plant-pathology-app
  template:
    metadata:
      labels:
        app: plant-pathology-app
    spec:
      containers:
      - name: plant-pathology-app-container
        image: plant-pathology-app
        ports:
        - containerPort: 443
        resources:
          requests:
            memory: 2048Mi
            cpu: 1
          limits:
            memory: 4096Mi
            cpu: 2
